import body

print(dir(body))

b = body.get(token='zalupa')
print(b)
print()
print(body.Add.filters(b))
print()
print(body.Add.filters(b, 'key', (1,2,3,4,5,6), 'to_str'))
print()
print(body.Add.filters(b, 'key', (1,2,3,4,5,6), 'to_list'))
print()
print(body.Add.order(b))
print()
print(body.Add.order(b, 'zalupa', 'desc'))
print()
print(body.Add.pagination(b))
print()
print(body.Add.pagination(b, page=10, limit=300))
print()
print(body.Add.column_search(b, 'govno', True))
print()
print(body.Add.payload(b, 'govno', True))
print()
print(body.Add.response_data(b))
print()
print(body.Add.response_data(b, ('items/zalupa')))

print(b)
